# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby
variables:
  azureSubscriptionEndpoint: opencell-lims-docker - Azure
  azureContainerRegistry: opencelllimsdockeracr.azurecr.io
  secretKey: $(secretKeyBase)
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DockerCompose@0
    displayName: Build Services
    inputs:
      action: Build services
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerComposeFile: docker-compose-ci.yml
  - task: DockerCompose@0
    displayName: Run tests
    inputs:
      action: Run a Docker Compose command
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerComposeFile: docker-compose-ci.yml 
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      dockerComposeCommand: run -e "RAILS_ENV=test" -e "CACHE_CLASSES=true" -e "RAILS_MASTER_KEY=$(masterKey)" -e "PERMITTED_IP=\d+\.\d+\.\d+\.\d+" web bundle exec rake db:create db:migrate db:seed spec
  - task: DockerCompose@0
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Build Services
    inputs:
      action: Build services
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      additionalImageTags: $(Build.BuildId)
      dockerComposeFile: docker-compose.prod.yml
      dockerComposeFileArgs: |
        SECRET_KEY=$(secretKey)
  - task: DockerCompose@0
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Push services
    inputs:
      action: Push services
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerComposeFile: docker-compose.prod.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: $(Build.BuildId)
      
